CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    age INT
);

INSERT INTO users (name, email, age)
VALUES
('Ali Khan', 'ali@gmail.com', 20),
('Ahmed Raza', 'ahmed@gmail.com', 21),
('Hassan Ali', 'hassan@gmail.com', 19),
('Usman Tariq', 'usman@gmail.com', 22),
('Hamza Malik', 'hamza@gmail.com', 20);

SELECT * FROM users;